server:
  port: ${APP_PORT:8080}
  servlet:
    application-display-name: Cloud Service

spring:
  application:
    name: cloudService

  datasource:
    url: jdbc:postgresql://localhost:5432/cloudService
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    hikari:
      schema: cloudService
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS "cloudService";

  config:
    use-legacy-processing: false

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    default-schema: cloudService
    liquibase-schema: cloudService
    change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  level:
    ROOT: INFO
    ru.netology: DEBUG
    org.springframework: INFO