version: '3.1'
services:
  postgres:
    image: postgres:12.7
    volumes:
      - ./uuid.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cloudService
    ports:
      - 5432:5432